### ISSUE TITLE
Error when closing shard while starting shards

### ISSUE THREAD

**Issue by TAG-Epic** [nextsnake/nextcore#175]
```py
await gateway.rescale_shards(5)
await gateway.close()
```

A fully reproducible test is coming in #162

**Comment by TAG-Epic** [comment]
Another error with same cause
```py
[22:18:28][nextcore.common.dispatcher][dispatcher.py:466][ERROR] Exception occured in event handler
Traceback (most recent call last):
  File "/home/epic/.cache/pypoetry/virtualenvs/nextcore-fOPpounq-py3.10/lib/python3.10/site-packages/nextcore/common/dispatcher.py", line 461, in _run_event_handler
    await maybe_coro(callback, *args)
  File "/home/epic/.cache/pypoetry/virtualenvs/nextcore-fOPpounq-py3.10/lib/python3.10/site-packages/nextcore/common/maybe_coro.py", line 54, in maybe_coro
    return await result
  File "/home/epic/.cache/pypoetry/virtualenvs/nextcore-fOPpounq-py3.10/lib/python3.10/site-packages/nextcore/gateway/shard.py", line 543, in _handle_hello
    await self._identify_flow()  # TODO: Better name?
  File "/home/epic/.cache/pypoetry/virtualenvs/nextcore-fOPpounq-py3.10/lib/python3.10/site-packages/nextcore/gateway/shard.py", line 392, in _identify_flow
    await self._identify()
  File "/home/epic/.cache/pypoetry/virtualenvs/nextcore-fOPpounq-py3.10/lib/python3.10/site-packages/nextcore/gateway/shard.py", line 699, in _identify
    await self._send(payload, wait_until_ready=False)
  File "/home/epic/.cache/pypoetry/virtualenvs/nextcore-fOPpounq-py3.10/lib/python3.10/site-packages/nextcore/gateway/shard.py", line 345, in _send
    assert (
AssertionError: Send rate limit was not set yet. Probably due to not receiving HELLO yet.
```
