### ISSUE TITLE
Weird asyncio runtime error on Windows. (Solved)

### ISSUE THREAD

**Issue by THEGOLDENPRO** [nextsnake/nextcore#189]
Hi, this is more of a question than a bug I'm hoping but how do I handle exceptions like `KeyboardInterrupt` in the example at https://github.com/nextsnake/nextcore/blob/master/examples/gateway/ping_pong.py

I would like to know this so I can perform some clean-ups in my program when the user does `CTRL + C` in the command line.

When I do `CTRL + C` in the cl right now I get this massive traceback which I'm not too sure is normal.
- **Traceback *(too long to drop here)*:** https://paste.nextcord.dev/?id=1675974727089914

## Result I want.
My keyboard interrupt to raise without that enormous traceback after.
```
I am able to catch the keyboard interrupt here owo
```
How do I go about this? How do I handle errors with ``wait_for()``. I believe I might be misunderstanding the usage here.

## Result I got.
```python
I am able to catch the keyboard interrupt here owo
....
Traceback (most recent call last):
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
....
```
> ***more traceback here:*** https://paste.nextcord.dev/?id=1675974727089914

# Code
```python
import asyncio
from typing import cast

from nextcore.gateway import ShardManager
from nextcore.http import BotAuthentication, HTTPClient

from decouple import config # Just using this for my token if you were wondering.

AUTHENTICATION = BotAuthentication(config("TOKEN"))
INTENTS = 1 << 9 | 1 << 15

http_client = HTTPClient()
shard_manager = ShardManager(
    AUTHENTICATION, 
    INTENTS, 
    http_client
)

async def main():
    await http_client.setup()

    await shard_manager.connect()

    error = await shard_manager.dispatcher.wait_for(lambda: True, "critical")

    # This is where I get a bit confused because my code never reaches this point when a Keyboard interrupt happens.

    raise cast(Exception, error)

try:
    asyncio.run(main())
except KeyboardInterrupt:
    print("I am able to catch the keyboard interrupt here owo") # This works but I still get that enormous traceback after.

# What I want is for my keyboard interrupt to raise with out that enormous traceback. How do I go about this?
```

**Comment by THEGOLDENPRO** [comment]
Alright, update. I fixed it. It now exits properly without all those tracebacks after including this line of code on windows:
```python
if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

I have no idea why this is the case on Windows but I've had previous issues like this before with asyncio.
